-- common_inbox_message
CREATE TABLE common_inbox_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL,

    CONSTRAINT uk_common_inbox_message_event_id UNIQUE (event_id)
);

-- unique constraint가 이미 인덱스를 생성하므로 사실상 중복이지만,
-- 엔티티의 @Index(name = "idx_inbox_event_id")와 맞추고 싶다면 추가
CREATE INDEX idx_inbox_event_id
    ON common_inbox_message (event_id);


-- common_outbox_message
CREATE TABLE common_outbox_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    topic VARCHAR(255) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    event_id VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,

    status VARCHAR(50) NOT NULL,

    user_id VARCHAR(255),
    user_role VARCHAR(255),
    user_email VARCHAR(255),

    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(45) NOT NULL,
    modified_at TIMESTAMP,
    modified_by VARCHAR(45),
    deleted_at TIMESTAMP,
    deleted_by VARCHAR(45),

    CONSTRAINT uk_common_outbox_message_event_id UNIQUE (event_id)
);

CREATE INDEX idx_outbox_agg_status_id
    ON common_outbox_message (aggregate_id, status, id);
